# Generated by Django 4.2.7 on 2023-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
