# Generated by Django 4.2.7 on 2023-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
