# Generated by Django 4.2.7 on 2023-12-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_author_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
