# Generated by Django 4.2.7 on 2023-12-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
