# Generated by Django 4.2.7 on 2023-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
