# Generated by Django 4.2.7 on 2023-12-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_comment_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replay',
        ),
        migrations.AddField(
            model_name='comment',
            name='praint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp1.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
