# Generated by Django 4.2.7 on 2023-12-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0015_alter_replay_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='praint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp1.comment'),
        ),
        migrations.DeleteModel(
            name='replay_comments',
        ),
    ]
