# Generated by Django 4.2.7 on 2023-12-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_comment_praint_delete_replay_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='praint',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='Author',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='Name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_posts', to='myapp1.author'),
        ),
    ]
