# Generated by Django 4.2.7 on 2023-12-27 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp1', '0018_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='likes',
            field=models.ManyToManyField(related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
