# Generated by Django 4.2.7 on 2024-01-02 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp1', '0020_rename_likes_author_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='like',
            field=models.ManyToManyField(blank=True, default=True, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
