# Generated by Django 4.2.7 on 2024-01-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpostapp.jobpost'),
        ),
    ]
