# Generated by Django 4.2.7 on 2024-01-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostapp', '0002_alter_apply_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job_type',
        ),
    ]
