# Generated by Django 4.2.7 on 2024-01-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostapp', '0003_remove_apply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job_type',
        ),
    ]
